image: python:3.10  # Use a Python environment

stages:
  - test
  - build
  - deploy

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - pytest test/  # Run tests

build:
  stage: build
  script:
    - python -m build  # Build the package

deploy:
  stage: deploy
  only:
    - main  # Deploy only from the main branch
  script:
    - pip install twine
    - twine upload --username "$PYPI_USERNAME" --password "$PYPI_PASSWORD" dist/*
